name: mindquest
description: A Flutter mental health gamification app
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  package_info_plus: ^9.0.0
  google_fonts: ^6.1.0
  fl_chart: ^1.1.1
  lucide_icons: ^0.257.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  url_launcher: ^6.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
  usage_stats: ^1.3.0
  permission_handler: ^12.0.1
  device_info_plus: ^12.3.0
  intl: ^0.20.2
  flutter_local_notifications: ^19.5.0
  confetti: ^0.8.0
  lottie: ^3.3.2
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.3.0
  flutter_secure_storage: ^9.0.0
  mailer: ^6.6.0
  crypto: ^3.0.6
  local_auth: ^3.0.0
  sensors_plus: ^7.0.0
  pedometer: ^4.0.0
  dio: ^5.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/


