name: mindquest
description: A Flutter mental health gamification app
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  package_info_plus: ^8.0.2
  google_fonts: ^6.2.1
  fl_chart: ^0.68.0
  lucide_icons: ^0.257.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  firebase_core: ^3.3.0
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.4.4
  url_launcher: ^6.3.0
  sqflite: ^2.3.3
  path: ^1.9.0
  usage_stats: ^1.3.0
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.2
  intl: ^0.19.0
  flutter_local_notifications: ^17.2.3
  confetti: ^0.7.0
  lottie: ^3.1.2
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.5.0
  flutter_secure_storage: ^9.2.2
  mailer: ^6.1.2
  crypto: ^3.0.5

  sensors_plus: ^5.0.1
  pedometer: ^4.0.3
  dtd: ^4.0.0
  flutter_lints: ^4.0.0
  json_rpc_2: ^3.0.0
  stack_trace: ^1.11.1
  web: ^1.0.0
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^6.1.1

  flutter_svg: ^2.0.7
  webview_flutter: ^4.8.0



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

